random-xs:
  candy_nsw:
    docker-tag: neurips23-ood-candy_nsw
    module: neurips23.ood.candy_nsw.candy_nsw
    constructor: candy_nsw
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "NSW"}]
        query-args: |
            [{"ef":30}, {"ef":50}, {"ef":100}]
text2image-10M:
  candy_nsw:
    docker-tag: neurips23-ood-candy_nsw
    module: neurips23.ood.candy_nsw.candy_nsw
    constructor: candy_nsw
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "NSW"}]
        query-args: |
          [{"ef":30}, {"ef":50}, {"ef":100}]
