random-xs:
  candy_nsw:
    docker-tag: neurips23-streaming-candy_nsw
    module: neurips23.streaming.candy_nsw.candy_nsw
    constructor: candy_nsw
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "NSW"}]
        query-args: |
            [{"ef":30}, {"ef":50}, {"ef":100}]
msturing-10M-clustered:
  candy_nsw:
    docker-tag: neurips23-streaming-candy_nsw
    module: neurips23.stremaing.candy_nsw.candy_nsw
    constructor: candy_nsw
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "NSW"}]
        query-args: |
          [{"ef":30}, {"ef":50}, {"ef":100}]
