random-xs:
  candy_mnru:
    docker-tag: neurips23-ood-candy_mnru
    module: neurips23.ood.candy_mnru.candy_mnru
    constructor: candy_mnru
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "MNRU32"}]
        query-args: |
            [{"ef":30}, {"ef":50}, {"ef":100}]
text2image-10M:
  candy_mnru:
    docker-tag: neurips23-ood-candy_mnru
    module: neurips23.ood.candy_mnru.candy_mnru
    constructor: candy_mnru
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "MNRU32"}]
        query-args: |
          [{"ef":30}, {"ef":50}, {"ef":100}]
