random-xs:
  candy_hnsw:
    docker-tag: neurips23-ood-candy_hnsw
    module: neurips23.ood.candy_hnsw.candy_hnsw
    constructor: candy_hnsw
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "HNSWNaive"}]
        query-args: |
            [{"ef":30}, {"ef":50}, {"ef":100}]
text2image-10M:
  candy_hnsw:
    docker-tag: neurips23-ood-candy_hnsw
    module: neurips23.ood.candy_hnsw.candy_hnsw
    constructor: candy_hnsw
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "HNSWNaive"}]
        query-args: |
          [{"ef":30}, {"ef":50}, {"ef":100}]
