random-xs:
  faiss_IVFPQ:
    docker-tag: neurips23-ood-faiss_IVFPQ
    module: neurips23.ood.faiss_IVFPQ.faiss_IVFPQ
    constructor: faiss_IVFPQ
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "IVF1024,SQ8"}]
        query-args: |
            [{"nprobe": 1}, {"nprobe": 4}, {"nprobe": 16}, {"nprobe": 64}]
text2image-10M:
  faiss_IVFPQ:
    docker-tag: neurips23-ood-faiss_IVFPQ
    module: neurips23.ood.faiss_IVFPQ.faiss_IVFPQ
    constructor: faiss_IVFPQ
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "IVF1024,SQ8"}]
        query-args: |
          [{"nprobe": 1}, {"nprobe": 4}, {"nprobe": 16}, {"nprobe": 64}]
